[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan config:cache; php -S 0.0.0.0:$PORT -t public & sleep 3; php artisan migrate --force; php artisan db:seed --force; wait"
