[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run build"
]

[start]
cmd = "php artisan config:cache; php artisan route:cache; php artisan view:cache; php artisan migrate --force; php artisan db:seed --force; sleep infinity"
