[phases.setup]
nixPkgs = ["nodejs_20", "nodePackages.npm"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm ci",
    "npm run build"
]

[start]
cmd = "export DB_CONNECTION=${DB_CONNECTION:-mysql}; php artisan config:cache; php artisan route:cache; php artisan view:cache; php artisan migrate --force; php artisan db:seed --force; php -S 0.0.0.0:$PORT -t public"
